# Generated by Django 3.1.3 on 2020-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date and time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.TextField(unique=True, verbose_name="name of product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date and time of creation"
            ),
        ),
    ]
