# Generated by Django 3.1.3 on 2020-11-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20201124_1407"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.TextField(
                choices=[("P", "Pictures"), ("L", "Logos")],
                verbose_name="type of product",
            ),
        ),
    ]
