# Generated by Django 3.1.3 on 2020-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20201126_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="price of product"
            ),
        ),
    ]
