# Generated by Django 3.1.3 on 2020-11-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_customer_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="productorder",
            options={
                "verbose_name": "ProductOrder",
                "verbose_name_plural": "ProductOrders",
            },
        ),
    ]
