# Generated by Django 3.1.3 on 2020-12-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_productbasket"),
    ]

    operations = [
        migrations.AddField(
            model_name="productbasket",
            name="session_key",
            field=models.CharField(default=None, max_length=128),
        ),
    ]
