# Generated by Django 3.1.3 on 2020-11-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.TextField(verbose_name="type of product")),
                ("product_name", models.TextField(verbose_name="name of product")),
                (
                    "product_price",
                    models.PositiveIntegerField(verbose_name="price of product"),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, verbose_name="description of product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="00000000000000",
                        max_length=13,
                        verbose_name="User number from telegram",
                    ),
                ),
                ("name", models.TextField(verbose_name="User name")),
                ("purchase", models.BooleanField(default=False)),
                (
                    "product",
                    models.TextField(blank=True, verbose_name="products to purchase"),
                ),
                (
                    "extra_message",
                    models.TextField(
                        blank=True, verbose_name="Some extra text from buyer"
                    ),
                ),
            ],
        ),
    ]
