# Generated by Django 3.1.3 on 2020-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testuser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="User number from telegram"
                    ),
                ),
            ],
        ),
    ]
