# Generated by Django 3.1.3 on 2020-11-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_testuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testuser',
        ),
    ]
