# Generated by Django 3.1.3 on 2020-11-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0003_delete_testuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
