# Generated by Django 3.1.3 on 2020-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0004_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                default="00000000000000",
                max_length=13,
                unique=True,
                verbose_name="User number from telegram",
            ),
        ),
    ]
