# Generated by Django 3.1.3 on 2020-11-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0005_auto_20201121_1707"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="purchase",
        ),
    ]
